name: Publish xprotoc-gen Docker image

on:
  push:
#    branches:
#      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./xprotoc-gen
          file: ./xprotoc-gen/Dockerfile
          push: true
#          tags: ${{ secrets.DOCKER_HUB_USER }}/xprotoc-gen:${{ steps.vars.outputs.TAG }}
          tags: ${{ secrets.DOCKER_HUB_USER }}/xprotoc-gen:latest
